generate bindings while using grouping with extension
when model (main-model) uses grouping from other model
 (grouping-model), which applies extension from other model
 (extension-model), generator can not find prefix for the extension,
 until the extension is manually imported to model (main-model), even
 when it is not used in model

missing also descriptive error log, problem had to be found by
 step-by-step debugging

[ERROR] yang-to-sources: Unable to generate sources with org.opendaylight.mdsal.binding.maven.api.gen.plugin.CodeGeneratorImpl generator
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Failed to find prefix for statement org.opendaylight.yangtools.yang.parser.rfc7950.stmt.extension.UnrecognizedStatementImpl@2b36caf5

Change-Id: I4a8d6701d42b86873c8f2d5258255d6f3a4f745c
Signed-off-by: Michal Banik <michal.banik@pantheon.tech>