Update patch set 4
Patch Set 4: Code-Review-1

Patch set 3 has been tested on Sandbox. The test failed due to too few flaps. Looking at karaf.log, two nodes contain messages like this:

2017-08-14 10:01:19,507 | INFO  | ult-dispatcher-5 | ClusterSingletonServiceGroupImpl | 155 - org.opendaylight.mdsal.singleton-dom-impl - 2.2.2.SNAPSHOT | Service group flapping-singleton-service ignoring lost ownership in state REGISTERED,

The remaining nodes has errors:

2017-08-14 10:00:31,598 | ERROR | rd-dispatcher-31 | ShardDataTree                    | 199 - org.opendaylight.controller.sal-distributed-datastore - 1.5.2.SNAPSHOT | member-2-shard-entity-ownership-operational: Failed to commit transaction member-1-entity-ownership-internal-fe-0-txn-446-0
java.lang.IllegalStateException: Store tree org.opendaylight.yangtools.yang.data.api.schema.tree.spi.MaterializedContainerNode@535bbddb and candidate base org.opendaylight.yangtools.yang.data.api.schema.tree.spi.MaterializedContainerNode@18f42b74 differ.

Full log is at https://logs.opendaylight.org/sandbox/jenkins091/controller-csit-3node-cs-chasing-leader-longevity-only-carbon/1/odl2_karaf.log.gz

Patch-set: 4
Label: Code-Review=-1