Update patch set 9
Patch Set 9:

Distcheck failure root cause:



44. NOK org.opendaylight.mdsal.dom-schema-service-osgi: OSGi state = Active, Karaf bundleState = Failure, due to: Blueprint
9/4/17 1:16 PM
Exception: 
java.lang.ClassNotFoundException: org.opendaylight.mdsal.dom.api.DOMSchemaService cannot be found by org.opendaylight.mdsal.dom-schema-service-osgi_2.4.0.SNAPSHOT
org.osgi.service.blueprint.container.ComponentDefinitionException: java.lang.ClassNotFoundException: org.opendaylight.mdsal.dom.api.DOMSchemaService cannot be found by org.opendaylight.mdsal.dom-schema-service-osgi_2.4.0.SNAPSHOT

Patch-set: 9
Label: Verified=0