compile error: missing symbol
change set in yangtool of e6eb03be17cbb50e446bae10b468a432dd9fc2b6
caused the following compilation error.

> [ERROR]
> /mdsal/binding/mdsal-binding-generator-impl/src/test/java/org/opendaylight/yangtools/sal/binding/yang/types/TypeProviderImplTest.java:[202,27]
> cannot find symbol
>   symbol:   method
>   setIdentity(org.opendaylight.yangtools.yang.model.api.IdentitySchemaNode)
>   location: variable identityRefBuilder of type
>   org.opendaylight.yangtools.yang.model.util.type.IdentityrefTypeBuilder

Change-Id: Ifb8aca3490fbca205dcdf848edb3538dc520bb15
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>