Bump vorburger.xtendbeans from 1.2.1 to 1.2.2 for mockito-core
see https://github.com/vorburger/xtendbeans/blob/master/CHANGES.md

must always use mockito-core instead of mockito-all 
to prevent NoSuchMethodError: org.hamcrest.Matcher ...

Bug 7662 related
Change-Id: Ib181e6b31ec0b905ca7e757d55add39d2a914f23
Signed-off-by: Michael Vorburger <vorburger@redhat.com>